pipeline {
  agent any
  tools {
    // a bit ugly because there is no `@Symbol` annotation for the DockerTool
    // see the discussion about this in PR 77 and PR 52:
    // https://github.com/jenkinsci/docker-commons-plugin/pull/77#discussion_r280910822
    // https://github.com/jenkinsci/docker-commons-plugin/pull/52
    'org.jenkinsci.plugins.docker.commons.tools.DockerTool' 'jenkins-docker'
    maven 'v3.8.6'
//     jdk 'jdk8'
  }
//   environment {
//     DOCKER_CERT_PATH = credentials('id-for-a-docker-cred')
//   }
  stages {
    stage('maven') {
      steps {
        sh "mvn -v"
      }
    }
    stage('docker') {
      steps {
        sh "docker -v"
      }
    }
  }
}