pipeline {
  agent any
  tools {
    'org.jenkinsci.plugins.docker.commons.tools.DockerTool' 'docker-17.05.0-ce'
    maven 'v3.8.6'
  }
//   environment {
//     DOCKER_CERT_PATH = credentials('id-for-a-docker-cred')
//   }
  stages {
    stage('maven') {
      steps {
         sh 'mvn -v'
         sh 'mvn clean package -Dmaven.test.skip=true'
      }
    }
    stage('docker') {
      steps {
        sh 'docker version'
      }
    }
    stage('docker2') {
      environment {
          MY_TOKEN = credentials('hub.docker')
      }
      steps {
        script{
          docker.withRegistry('https://hub.docker.com','$MY_TOKEN'){
            def customImage = docker.build("my-image:${env.BUILD_ID}")

            /* Push the container to the custom Registry */
            customImage.push()
          }
        }
      }
    }
  }
}